### ISSUE TITLE
error in runing test.py 

### ISSUE THREAD

**Issue by LeeyMessi** [waldeland/CNN-for-ASI#10]
hello, Sir, sorry to bother you!  As follows, I  meet a error when runing test.py.
`Interpolating down sampled results to fit input cube
Traceback (most recent call last):
  File "test.py", line 64, in <module>
    classified_cube  = interpret( network.classify, data, data_info, 'full', None, im_size, 16, use_gpu=use_gpu)
  File "/home/leeyang/data/cnn_asi/utils.py", line 123, in interpret
    class_cube[i] = interpn(pred_points, class_cube[i].astype('float').squeeze(), grid_output_cube, method='linear', fill_value=0, bounds_error=False)
  File "/home/leeyang/anaconda3/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 2648, in interpn
    return interp(xi)
  File "/home/leeyang/anaconda3/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 2481, in __call__
    indices, norm_distances, out_of_bounds = self._find_indices(xi.T)
  File "/home/leeyang/anaconda3/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 2529, in _find_indices
    norm_distances.append((x - grid[i]) /
MemoryError
`
Have you meet such a problem?

**Comment by waldeland** [comment]
Hi LeeyMessy,

The clue is in the error-log: "... MemoryError". Linear interpolation requires a lot of memory (linearly scalable with the size of the cube). You can try with a smaller cube, or on a computer with more memory.

Best regards
Anders
