### ISSUE TITLE
Visualize data

### ISSUE THREAD

**Issue by dimitrisl** [waldeland/CNN-for-ASI#6]
Hello,

While trying to visualize the Test logs i ran : tensorboard --logdir=log/* (i mean for every possible subfolder) since the tensorboard --outditr=log didn't work.

But even though there are logs in the log/train and the log/test folder tensorboard does not seem to be able to see them! ( i use tensorboard 1.5.1)
Any thoughts?

Thanks in advance

--Dimitris

**Comment by waldeland** [comment]
Hi,
it should without the asterix (*). Tensorboard already look into subfolders.

**Comment by dimitrisl** [comment]
Hello again,

Thank you very much for the response,
I've already tried that without any effect

**Comment by waldeland** [comment]
What happens when you try to run: tensorboard --logdir=log/ ?

**Comment by dimitrisl** [comment]
i get 

```
` dimitrisl@desktop-dl:~/Projects/CNN-for-ASI$ tensorboard --logdir=log/
Exception in thread Reloader:
Traceback (most recent call last):
  File "/home/dimitrisl/miniconda3/envs/SDetection/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/dimitrisl/miniconda3/envs/SDetection/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dimitrisl/miniconda3/envs/SDetection/lib/python3.6/site-packages/tensorboard/backend/application.py", line 361, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/home/dimitrisl/miniconda3/envs/SDetection/lib/python3.6/site-packages/tensorboard/backend/application.py", line 335, in reload_multiplexer
    multiplexer.Reload()
  File "/home/dimitrisl/miniconda3/envs/SDetection/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 195, in Reload
    accumulator.Reload()
  File "/home/dimitrisl/miniconda3/envs/SDetection/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 185, in Reload
    for event in self._generator.Load():
  File "/home/dimitrisl/miniconda3/envs/SDetection/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 88, in Load
    for event in self._LoadInternal():
  File "/home/dimitrisl/miniconda3/envs/SDetection/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 112, in _LoadInternal
    for event in self._loader.Load():
  File "/home/dimitrisl/miniconda3/envs/SDetection/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 53, in Load
    self._reader.GetNext(status)
TypeError: GetNext() takes 1 positional argument but 2 were given

TensorBoard 1.5.1 at http://desktop-dl:6006 (Press CTRL+C to quit)

`
```
and when i open the link tensorboard cannot locate the logs

**Comment by waldeland** [comment]
Seems to be realted to this issue: https://github.com/tensorflow/tensorboard/issues/1111

After reading the disucssion, my best guess would be to update tensorboard to the newest version. My second best guess would be to make sure that the tensorboard-log files are produced with the same version of tensorboard that you try to view them with.

Other than that I am not sure what might be the problem.

Good luck, and thanks for getting in touch.

**Comment by dimitrisl** [comment]
Thanks!
It seems upgrading it to tensorboard 1.8 did the trick!

**Comment by mtkilic** [comment]
I have same issue, but I have tensorboard 1.13.0 version.  I feel like I am doing something wrong, where the log files should be exported? because I dont see any log folder in the directory

**Comment by waldeland** [comment]
They should be created within the log-directory.

**Comment by mtkilic** [comment]
I get below output when I Ctrl + C, is this expected? 
Image                        PC                           Routine            Line          Source
libifcoremd.dll       00007FF95E1294C4    Unknown         Unknown  Unknown
KERNELBASE.dll     00007FF996D856FD   Unknown         Unknown  Unknown
KERNEL32.DLL       00007FF998B33034    Unknown         Unknown  Unknown
ntdll.dll                  00007FF99A7E3691    Unknown          Unknown  Unknown

**Comment by mtkilic** [comment]
Update
Running as below doesn't create log directory
>>>tensorboard --logdir="log"
However, running below code will create log directory
>>>python batch.py --logdir="log"
at first you get couple python error, but fixing those and running again will create log-directory and i am able to see it on tensorboard
